### ISSUE TITLE
references/sources to incorporate into the guidelines

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/SoftwareDevelopmentGuidelines#3]
https://codecheck.org.uk/guide/community-process

**Comment by sanjayankur31** [comment]
* [Python best practices](https://python-best-practices-software-that-just-works.readthedocs.io/)
* [Guide for Reproducible Research (The Turing Way)](https://the-turing-way.netlify.app/reproducible-research/reproducible-research.html)
* [Best Practices for Scientific Computing](https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.1001745)
* [Good enough practices in scientific computing](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005510)

**Comment by sanjayankur31** [comment]
- [Research Software Criteria and Taxonomy](https://rseng.github.io/rseng/)

**Comment by brenthuisman** [comment]
The Software Sustainability Institute has a bunch of guides: https://www.software.ac.uk/guides
Not very specific to research software, but still interesting: a label that you can earn if you meet certain requirements: https://bestpractices.coreinfrastructure.org/

**Comment by sanjayankur31** [comment]
Ran into this:

- [CII Best practices](https://bestpractices.coreinfrastructure.org/en)

**Comment by brenthuisman** [comment]
@sanjayankur31 Perhaps in the post above ;)

Meanwhile I pulled Arbor through that wringer: https://bestpractices.coreinfrastructure.org/en/projects/4476
We fail at process around security, but I think that does not really apply to our kind of projects.
We don't do any static analysis or fuzzing in our CI as a matter of course, I'd be curious if anyone else here does and how they handle the probably very long list of 'problems' coming out of that. We've found that different tools produce very different outputs, and very different quality of outputs.

**Comment by sanjayankur31** [comment]
Oh, I thought I'd run into it from a different project :laughing: 

Yes, I don't think all the points for general infrastructure projects apply to research projects---we'll cherry-pick the relevant ones.

With software that we package in NeuroFedora, the Red Hat security team tends to do regular audits so we do get CVE reports from time to time ([Example](https://bugzilla.redhat.com/show_bug.cgi?id=1848468)). But, I'll have to double-check if they audit the complete set of thousands of packages included in Fedora and EL, or if they pick ones that are important for their own work/customers.

**Comment by sanjayankur31** [comment]
- [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0-beta.2/): seems to allow automatic generation of changelogs also
- [Semantic Versioning 2.0.0 | Semantic Versioning](https://semver.org/)

**Comment by sanjayankur31** [comment]
[Google Style Guides | styleguide](https://google.github.io/styleguide/):

> This project holds the C++ Style Guide, C# Style Guide, Swift Style Guide, Objective-C Style Guide, Java Style Guide, Python Style Guide, R Style Guide, Shell Style Guide, HTML/CSS Style Guide, JavaScript Style Guide, TypeScript Style Guide, AngularJS Style Guide, Common Lisp Style Guide, and Vimscript Style Guide. This project also contains cpplint, a tool to assist with style guide compliance, and google-c-style.el, an Emacs settings file for Google style.

**Comment by brenthuisman** [comment]
Some more:

* [xSDK](https://xsdk.info/download/): The xSDK, which provides the foundation of an extensible scientific software ecosystem, began within the IDEAS scientific software productivity project with support from the DOE Office of Science, Offices of Advanced Scientific Computing Research (ASCR) and Biological and Environmental Research (BER).
* [BSSW/PSIP](https://bssw.io/blog_posts/productivity-and-sustainability-improvement-planning-psip) Scientific software teams are typically focused on the creation of a new set of features that will enable the next set of computational experiments. Teams seldom have the time to stop development and focus solely on improving productivity or sustainability. However, teams can incorporate improvements on the way to developing new science capabilities. The Productivity and Sustainability Improvement Planning (PSIP) process recognizes that productivity and sustainability improvements for scientific software benefit from an incremental, iterative approach.
  * An actionable outcome: http://rateyourproject.org, something a bit more high level than http://bestpractices.org

**Comment by sanjayankur31** [comment]
List of licenses with identifiers: https://spdx.org/licenses/
