### ISSUE TITLE
References for Python guidelines

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/SoftwareDevelopmentGuidelines#4]
Please collect Python specific bits here.

**Comment by sanjayankur31** [comment]
- [Python PEPs (Python Enhancement Proposals)](https://www.python.org/dev/peps/)
- [Python docstring formats](https://stackoverflow.com/a/24385103/375067)

**Comment by sanjayankur31** [comment]
- [Pylint](http://pylint.pycqa.org/en/latest/)
- [Flake8: Your Tool For Style Guide Enforcement](https://flake8.pycqa.org/en/latest/index.html)

**Comment by brenthuisman** [comment]
Python docstrings and Sphinx: [Napoleon](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/)
Doxygen/Sphinx integration: [Breathe](https://breathe.readthedocs.io/en/latest/), [Exhale](https://exhale.readthedocs.io/en/latest/)
Doxygen alternative: https://www.copperspice.com/docs/doxypress/index.html

**Comment by mstimberg** [comment]
Very relevant initiative in general: https://www.pyopensci.org/
Here their requirements for packages they review: https://www.pyopensci.org/contributing-guide/authoring/overview.html
I like their approach of having good/better/best recommendations (I think I mentioned this somewhere already, but at the time I did not have the link at hand) – it avoids making recommendations/requirements feel unachievable for "common researchers" (of the form "you definitely need to provide a docker container, make sure to set up your own testing server, so you can test run your software on exotic hardware, and if your lines are longer than 79 character, don't even bother publishing it").

**Comment by sanjayankur31** [comment]
Looks very good. I'll update my WIP to use this system. Not been able to find a lot of time to work on these yet, unfortunately.

**Comment by sanjayankur31** [comment]
[Structuring Your Project — The Hitchhiker's Guide to Python](https://docs.python-guide.org/writing/structure/)

For new projects

**Comment by mstimberg** [comment]
A forthcoming book (also freely available under CC license): [ Research Software Engineering with Python](https://merely-useful.tech/py-rse/)

**Comment by mstimberg** [comment]
"This is a tutorial with a template for packaging, testing, documenting, and publishing scientific Python code."
[scientific-python-cookiecutter](https://nsls-ii.github.io/scientific-python-cookiecutter/index.html)

**Comment by mstimberg** [comment]
> ### Writing good research code
>
> This repo contains the slides and code for a presentation on writing research software I first gave in January 2021 to the PhD students in neuro at Harvard. It's a compendium of 5 lessons I learned the hard way about writing research code that won't bite 
back.

https://github.com/patrickmineault/research_code

**Comment by mstimberg** [comment]
Patrick Mineault now turned the material from my previous comment into a handbock: https://goodresearch.dev
